In [ ]:
#VARIBLE
a=10
print("I am 10 years old")

T am 10 years old


In [ ]:
#ADD TWO NUMBERS
a=int(input("enter a value"))
b=int(input("enter b value"))
c=a+b
print(c)

enter a value4
enter b value5
9


In [ ]:
#arithematic operations
a=int(input("enter a value"))
b=int(input("enter b value"))
print("sum is = ",a+b)
print("differnce is = ",a-b)
print("product is = ",a*b)
print("remainder is = ",a%b)
print("power of a is = ",a**b)
print("quotient is = ",a/b)
print("floor division is = ",a//b)

enter a value6
enter b value8
sum is =  14
differnce is =  -2
product is =  48
remainder is =  6
power of a is =  1679616
quotient is =  0.75
floor division is =  0


In [ ]:
#take the numbers from the user(salary) if the salary is more than 50k their is a 10% tax print his final salary
n=int(input("Enter salary : "))
if (n>50000):
  print("salary is : ",n-n*0.1)
else:
  print("salary is less than 50000")



Enter salary : 700000000
salary is :  630000000.0


In [ ]:
#get the salary from user if the salary is more or equal to 50 thousand then apply 10% tax deduction if the salary is less than 50 thousand the apply the 5% tax if the salary is more than 70 thousand apply 12%tax if the salary exits 1Lakh print your are promoted
n=int(input("Enter salary : "))
if (n<=50000):
  print("salary with 5% tax deduction  : ",n-n*(5/100))
if (n>50000 and n<70000):
  print("salary with 10% tax deduction  : ",n-n*0.1)
elif (n>=70000 and n<=100000):
  print("salary with 12% tax deduction  : ",n-n*(12/100))

else:
  print("your are promoted ")





Enter salary : 100500
your are promoted 


In [ ]:
#for loop
for i in range(1,10,1):
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
#for loop for table
n=int(input("enter a number : "))
for i in range(1, 11):
    print(n , "x",i, "=", n *i )
    print()

enter a number : 7
7 x 1 = 7

7 x 2 = 14

7 x 3 = 21

7 x 4 = 28

7 x 5 = 35

7 x 6 = 42

7 x 7 = 49

7 x 8 = 56

7 x 9 = 63

7 x 10 = 70



In [ ]:
n=int(input("enter number : "))
i=1
while(i<=10):
  print(n,"x",i, '=', n*i)
  i=i+1


enter number : 89
89 x 1 = 89
89 x 2 = 178
89 x 3 = 267
89 x 4 = 356
89 x 5 = 445
89 x 6 = 534
89 x 7 = 623
89 x 8 = 712
89 x 9 = 801
89 x 10 = 890


In [ ]:
#create a list
list=[1,2,3,4,]
print(list)

[1, 2, 3, 4]


In [ ]:
#list
l1=[9,'ravi','#',67,'kumar']
for i in l1:

  print(i)

9
ravi
#
67


In [ ]:
#add the element in last
l1.append('appended')
print(l1)

[9, 'inserted', 'ravi', '#', 67, 'inserted', 'appended']


In [ ]:
#deleting using index number
l1.pop(6)#listname.pop(index)
print(l1)

[9, 'inserted', 'ravi', '#', 67, 'inserted']


In [ ]:
#insert the element by index position
l1.insert(-3,89)#listname.insert(index position , element)
print(l1)

[9, 'inserted', 'ravi', 89, '#', 67, 'inserted']


In [ ]:
l1.pop(3)
print(l1)

[9, 'inserted', 'ravi', '#', 67, 'inserted']


In [ ]:
#remove is used to delete the num/char in list
l1.remove(67)#listname.remove(element)
print(l1)


[9, 'inserted', 'ravi', '#', 'inserted']


In [ ]:
l1.clear()#listname.clear()
print(l1)

[]


In [ ]:
#create a list of 10 integer elements print there squares
#save this list in new list
l=[1,2,3,4,5,6,7,9,8,23]
m=[]
for i in l:
  m.append(i*i)
print(m)

[1, 4, 9, 16, 25, 36, 49, 81, 64, 529]


In [ ]:
#list comperhension
#syntax
#newlist = [output for loop]
l1=[1,2,3,4,5,6,7,8,9,12]
r=[i*i for i in l1]
print(r)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 144]


In [ ]:
#newlist = [output for loop if condition]
l1=[1,2,3,4,5,6,7,8,9,12]
r=[i*i for i in l1 if i>5]
print(r)

[36, 49, 64, 81, 144]


In [ ]:
#syntax
#newlist = [(statment of if) if (cond) else (st of else) for loop]
l1=[1,2,3,4,5,6,7,8,9,12]
r=[i*i if i>5 else 'x' for i in l1 ]
print(r)

['x', 'x', 'x', 'x', 'x', 36, 49, 64, 81, 144]


In [ ]:
#take the salary from the user if the salary is less than 50k then 10% tax otherwise 15% tax
n=[780000,340000,500000,1000,2000000]
l=[(i-(i*10/100)) if i<500000 else (i-(i*15/100)) for i in n]
print(l)

[663000.0, 306000.0, 425000.0, 900.0, 1700000.0]


In [ ]:
#create a dictionary
dict1={1:'ravi',2:'kumar',3:'yugi',4:'kish'}
print(dict1)

{1: 'ravi', 2: 'kumar', 3: 'yugi', 4: 'kish'}


In [ ]:
#check the dupicate of dict
dict1={1:'ravi',1:'kumar',3:'yugi',4:'kish'}
print(dict1)

{1: 'kumar', 3: 'yugi', 4: 'kish'}


In [ ]:
print(dict1.keys())
print(dict1.values())

dict_keys([1, 3, 4])
dict_values(['kumar', 'yugi', 'kish'])


In [ ]:
dict1[1]

'kumar'

In [ ]:
dict2={'dept':'CSE','details': {'sec':'D','year':2,'count':71}}
print(dict2)
print("year is ",dict2["details"]["year"])
print("count is ",dict2["details"]["count"])
print("sec is ",dict2["details"]["sec"])

{'dept': 'CSE', 'details': {'sec': 'D', 'year': 2, 'count': 71}}
year is  2
count is  71
sec is  D


In [ ]:
dict3=[34,45,67,78,400]
names=['ravi','kumar','ajay','kishore','yugi']
new_zip=(zip(dict3,names))
for i in new_zip:
  print(i)

(34, 'ravi')
(45, 'kumar')
(67, 'ajay')
(78, 'kishore')
(400, 'yugi')


In [ ]:
#numpy
import numpy as np
A = np.array([1,2,3,4]) #1d array
print(A.ndim)
print(A.shape)


1
(4,)


In [ ]:
# 2-dimension
B = np.array([[2,3,4,5],[6,4,7,8],[9,8,7,6,]])#2d array
#elements in each row = columns
print(B.ndim)
print(B.shape)
print(B)


2
(3, 4)
[[2 3 4 5]
 [6 4 7 8]
 [9 8 7 6]]


In [ ]:
#3-dimension
C= np.array([[[1,2,3,4],[5,6,7,8],],[[9,8,7,6],[8,4,5,3]]])
print(C.ndim)
print(C.shape)
print(C)

3
(2, 2, 4)
[[[1 2 3 4]
  [5 6 7 8]]

 [[9 8 7 6]
  [8 4 5 3]]]


In [ ]:
R= np.zeros((2,4,3))
print(R)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
A=np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A=np.arange(1,10,2)#start,stop,step
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers divisible by 8 using arange function btw 1 to 100
A=np.arange(8,1001,8)#start,stop,step
print(A)
print(type(A))

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]
<class 'numpy.ndarray'>


In [ ]:
#splitting the range into n  numbers having common difference
A= np.linspace(48,78,10)
print(A)


[48.         51.33333333 54.66666667 58.         61.33333333 64.66666667
 68.         71.33333333 74.66666667 78.        ]


In [5]:
#tuple,set,collab file,documentation,



#tuples
t=(1,2,3,4,5)
print(t)
#concat
t1=(1,2,3)+(4,5,6,3)
print(t1)
#lenght
print(len(t))
#repetition
t2=("hi! ")*4
print(t2)
#in
print(3 in t1)
#index
print(t[0])
print(t[0:4])
#updating tuple using list
tl=list(t)
tl[1]=55
t=tuple(tl)
print(t)
#type
print(type(t))
#count
print(t.count(5))
#index
print(t.index(5))









#SET OPERTION
#set operations
s1={1,2,3,4,5}
s2={4,5,6,7,8}
#union
print(s1.union(s2))
#intersection
print(s1.intersection(s2))
#difference
print(s1.difference(s2))
#symmetric_difference
print(s1.symmetric_difference(s2))
#subset
print(s1.issubset(s2))
#superset
print(s1.issuperset(s2))
#disjoint
print(s1.isdisjoint(s2))












































(1, 2, 3, 4, 5)
(1, 2, 3, 4, 5, 6, 3)
5
hi! hi! hi! hi! 
True
1
(1, 2, 3, 4)
(1, 55, 3, 4, 5)
<class 'tuple'>
1
4
{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
{1, 2, 3}
{1, 2, 3, 6, 7, 8}
False
False
False


In [6]:
#sort
a=[9,4,6,2,5]
a.sort()
print(a)

[2, 4, 5, 6, 9]


In [7]:
a=[9,4,7,2,6,3]
b=sorted(a)
print(b)

[2, 3, 4, 6, 7, 9]
