In [ ]:






import numpy as np
a=np.arange(1,13).reshape(3,4)
        #(start,stop)     (rows,columns)
print(a)
a=np.linspace(2,8,12).reshape(6,2)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2.         2.54545455]
 [3.09090909 3.63636364]
 [4.18181818 4.72727273]
 [5.27272727 5.81818182]
 [6.36363636 6.90909091]
 [7.45454545 8.        ]]


In [ ]:
#resize :
#->changes the shape of original array
#reshape : changes needs saving in another variable
import numpy as np
b=np.array([45,67,89,12,34,51,90,98]).reshape(2,2,2)
b

array([[[45, 67],
        [89, 12]],

       [[34, 51],
        [90, 98]]])

In [ ]:
#matrix subtraction
a = np.array([34,56,78,90])
b = np.array([7,4,8,3])   #list will throw an error while arrays iterate themselves
c=a-b
c


array([27, 52, 70, 87])

In [ ]:
#matrix addition
a = np.array([34,56,78,90])
b = np.array([7,4,8,3])
c=a+b
c

array([41, 60, 86, 93])

In [ ]:
#matrix multiple
a = np.array([34,56,78,90]).reshape(2,2)
b = np.array([7,4,8,3]).reshape(2,2)
print(a)
print("________")
print(b)
c=a*b
print("___________")
c

[[34 56]
 [78 90]]
________
[[7 4]
 [8 3]]
___________


array([[238, 224],
       [624, 270]])

In [ ]:
#matrix multipication
a = np.array([34,56,78,90]).reshape(2,2)
b = np.array([7,4,8,3]).reshape(2,2)
print(a)
print("________")
print(b)
c=a@b
print("___________")
c

[[34 56]
 [78 90]]
________
[[7 4]
 [8 3]]
___________


array([[ 686,  304],
       [1266,  582]])

In [ ]:
#matrix maximum and minimum
a = np.array([34,56,78,90])
print(a.max())
print(a.min())

90
34


In [ ]:
#matrix maimum and minmum using rows and columns
a = np.array([34,90,16,56,77,44,66,22,99,33,100,111]).reshape(4,3)

print(a)
print("________")
print(a.max(axis=0)) #axis 0 -column
print("___________")
print(a.max(axis=1)) #axis 1 -row


[[ 34  90  16]
 [ 56  77  44]
 [ 66  22  99]
 [ 33 100 111]]
________
[ 66 100 111]
___________
[ 90  77  99 111]


In [ ]:
#vertical array and horizontal
a = np.array([34,56,78,90]).reshape(2,2)
b = np.array([7,4,8,3]).reshape(2,2)
print(a)
print("________")
print(b)
print("_________")
print("after vertical stacking the array")
print(np.vstack((a,b),))
print("after horizontal stacking the array")
print(np.hstack((a,b),))

[[34 56]
 [78 90]]
________
[[7 4]
 [8 3]]
_________
after vertical stacking the array
[[34 56]
 [78 90]
 [ 7  4]
 [ 8  3]]
after horizontal stacking the array
[[34 56  7  4]
 [78 90  8  3]]


In [ ]:
a = np.array([34,56,78,90]).reshape(2,2)
b = np.array([7,4,8,3]).reshape(2,2)
print(a)
print("________")
print(b)
print("_________")
print("after vertical stacking the array")
print(np.stack((a,b),axis = 0))
print("after horizontal stacking the array")
print(np.stack((a,b),axis = 1))

[[34 56]
 [78 90]]
________
[[7 4]
 [8 3]]
_________
after vertical stacking the array
[[[34 56]
  [78 90]]

 [[ 7  4]
  [ 8  3]]]
after horizontal stacking the array
[[[34 56]
  [ 7  4]]

 [[78 90]
  [ 8  3]]]


In [ ]:
#dimension stack - interchange of rows to columns
a=np.arange(30).reshape(2,3,5)    #(g,r,c)
print(a)
print("after dstack")    #no.of rows = no. of group
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
after dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#splitting arrays!
a= np.arange(18).reshape(6,3)
print(a)
print("after splitting")
np.vsplit(a,3)   #(array name , split no)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#splitting arrays! virtically
a= np.arange(18).reshape(6,3)
print(a)
print("after splitting")
np.vsplit(a,(2,5)) #(array name , position of first split , where to stop )

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [ ]:
#splitting arrays!-----------horizontaly
a= np.arange(18).reshape(6,3)
print(a)
print("after splitting")
np.hsplit(a,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]

In [ ]:
#splitting arrays! virtically
a= np.arange(18).reshape(6,3)
print(a)
print("after splitting")
np.hsplit(a,(2,5)) #(array name , position of first split , where to stop )

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13],
        [15, 16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([], shape=(6, 0), dtype=int64)]

In [ ]:
a = np.array([17,4,18,12,45,89,67,49,35,72,56,46]).reshape(3,4)
print(a)
print(a.argmax(axis = 1))

[[17  4 18 12]
 [45 89 67 49]
 [35 72 56 46]]
[2 1 1]


In [ ]:
a = np.array([17,4,18,12,45,89,67,49,35,72,56,46]).reshape(3,4)
print(a)
print(a.argmax(axis = 0))    #position     #column          #column
                                        # 0 0 0             # 0 1 2
                                        # 1 1 1             # 0 1 2
                                        # 2 2 2             # 0 1 2


[[17  4 18 12]
 [45 89 67 49]
 [35 72 56 46]]
[1 1 1 1]


In [ ]:
a = np.array([17,4,18,12,45,89,67,49,35,72,56,46]).reshape(3,4)
print(a)
print(a.argmin(axis = 0))

[[17  4 18 12]
 [45 89 67 49]
 [35 72 56 46]]
[0 0 0 0]


In [ ]:
a = np.array([17,4,18,12,45,89,67,49,35,72,56,46]).reshape(3,4)
print(a)
print(a.argmin(axis = 1))

[[17  4 18 12]
 [45 89 67 49]
 [35 72 56 46]]
[1 0 0]


In [ ]:
# mean median var std
a = np.array([12,34,66,71,88])
print("mean : " ,np.mean(a))
print("median : ",np.median(a))
print("variance : ",np.var(a))
print("standand dev : ",np.std(a))

mean :  54.2
median :  66.0
variance :  750.5599999999998
standand dev :  27.39635012186842


In [ ]:
a = np.pi    #radians
a             #pi=180

3.141592653589793

In [ ]:
np.rad2deg(a)    # radians to degree

180.0

In [ ]:
b=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
np.rad2deg(b)

array([ 45.,  60.,  90., 180.])

In [ ]:
a=np.array([30,45,60,90,120,180])
b=np.deg2rad(a)
print(b)

[0.52359878 0.78539816 1.04719755 1.57079633 2.0943951  3.14159265]


In [ ]:
np.tan(a)    #tan values

array([-6.4053312 ,  1.61977519,  0.32004039, -1.99520041,  0.71312301,
        1.33869021])

In [ ]:
np.cos(a)      #cos values

array([ 0.15425145,  0.52532199, -0.95241298, -0.44807362,  0.81418097,
       -0.59846007])

In [ ]:
np.sin(a)       #sin values

array([-0.98803162,  0.85090352, -0.30481062,  0.89399666,  0.58061118,
       -0.80115264])

In [ ]:
np.arcsin(1)     #sin^-1

1.5707963267948966

In [ ]:
np.arctan(1)      #tan^-1

0.7853981633974483

In [ ]:
np.arccos(1)      #cos^-1

0.0

In [ ]:
# search of a array
a=np.array([90,45,34,23,56,78])
print(np.where(a==45))

(array([1]),)


In [2]:
# search of a array
import numpy as np
a=np.array([90,45,34,23,56,78])
print(np.where(a%2==0))           #returns the even positions

(array([0, 2, 4, 5]),)


In [12]:
#search sorted
a=np.array([12,23,34,45,21])
print(np.searchsorted(a,21))
#12 21 23 34 45

1


Linear and UFunc

In [22]:
a = np.array([6,34,2,67,8])
b= np.array([5,12,4,1,3])
print(np.add(a,b))
print(np.divide(a,b))
print(np.divmod(a,b))
print(np.subtract(a,b))
print(np.sort(a))
print(np.sort(b))
print(np.mod(a,b))
print(np.diff(a))
print(np.diff(b))
print(np.multiply(a,b))
print(np.union1d(a,b))
print(np.setdiff1d(a,b))
print(np.intersect1d(a,b))
print(np.trunc(a))
print(np.around(a))
print(np.floor(a))


[11 46  6 68 11]
[ 1.2         2.83333333  0.5        67.          2.66666667]
(array([ 1,  2,  0, 67,  2]), array([ 1, 10,  2,  0,  2]))
[ 1 22 -2 66  5]
[ 2  6  8 34 67]
[ 1  3  4  5 12]
[ 1 10  2  0  2]
[ 28 -32  65 -59]
[ 7 -8 -3  2]
[ 30 408   8  67  24]
[ 1  2  3  4  5  6  8 12 34 67]
[ 2  6  8 34 67]
[]
[ 6. 34.  2. 67.  8.]
[ 6 34  2 67  8]
[ 6. 34.  2. 67.  8.]


In [18]:
a = np.array([6,24,60,12,18])
b = np.array([6,4,10,5,4])
print(np.intersect1d(a,b))


[6]


In [21]:
#rounding
a1=np.round(3.2345,3)
a1

3.234

In [23]:
a1=np.around(3.2345,3)
a1

3.234

In [27]:
a1 = np.floor(np.array([-3.2345, 3.6666]))
a1

array([-4.,  3.])

In [29]:
a1 = np.fix(np.array([-3.2345, 3.6666]))
a1

array([-3.,  3.])

In [30]:
a = np.array([3,4,6,34,78,48])
print(np.cumprod(a))

[      3      12      72    2448  190944 9165312]


In [31]:
a = np.array([3,4,6,34,78,48])
print(np.cumsum(a))

[  3   7  13  47 125 173]


In [32]:
np.lcm(445,555)


49395

In [35]:
np.gcd(445,555)

5

In [38]:
a= np.array([45,65,30])
print(np.lcm.reduce(a))
print(np.gcd.reduce(a))

1170
5


In [37]:
print(np.lcm(445,555))

np.gcd(445,555)

49395


5

In [39]:
a= np.array([[1,2],[3,4]])
print(np.linalg.inv(a))      #it gives inverse of matrix a

[[-2.   1. ]
 [ 1.5 -0.5]]


In [46]:
import random as rd
A= rd.random() # default limit 0 to 99   #rand(n)
print(A)

0.46060036319310327


In [51]:
A= rd.randint(1,4)
print(A)

4


In [52]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.outer(a,b))    #

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [53]:
#joins
a=np.array([1,2,3])
b=np.array([4,5,6])
#1*4 + 2*5 + 3*6 =32
print(np.inner(a,b))

32


In [54]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.cross(a,b))

[-3  6 -3]
